import type { Metadata } from "next";
import "./globals.css";
import { Inter, Inter_Tight } from "next/font/google";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nextjango",
  description: "Generated by Nextjango",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${interTight.variable} antialiased`}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
