"use client";

import { useEffect, useState } from "react";
import { checkHealth } from "./health";

/**
 * Default page served by new Next.js applications generated by Nextjango.
 * Displays the backend health status on load.
 */
export default function Page() {
  const [message, setMessage] = useState("Checking backend...");

  useEffect(() => {
    checkHealth()
      .then((data) => setMessage(`Backend status: ${data.status}`))
      .catch(() => setMessage("Backend unreachable"));
  }, []);

  return <h1>{message}</h1>;
}
