"use client";

import { useEffect, useState } from "react";
import { checkHealth } from "./health";
import Hero from "../components/Hero";
import AnimatedGridBackground from "../components/AnimatedGridBackground";

/**
 * Default page served by new Next.js applications generated by Nextjango.
 * Displays the backend health status on load.
 */
export default function Page() {
  const [message, setMessage] = useState("Checking backend...");
  const [isConnected, setIsConnected] = useState(false);

  useEffect(() => {
    checkHealth()
      .then((data) => {
        setMessage(`Backend status: ${data.status}`);
        if (data.status === "ok" || data.status === "healthy") {
          setIsConnected(true);
        }
      })
      .catch(() => setMessage("Backend unreachable"));
  }, []);

  return (
    <main>
      <AnimatedGridBackground />
      <Hero />
    </main>
  );
}
